### ISSUE TITLE
Cemu Motion Patches do not work

### ISSUE THREAD

**Issue by Uzi043** [git-developer/batocera-extra#10]
Apologies for my ignorance, I'm very inexperienced when it comes to these sort of things.

I'm trying to apply EXTRA_PATCHES and MOTION_EVDEV to Cemu so I can use my 8BitDo to play Breath of the Wild on Wii U with motion controls. Whenever I boot the game, it crashes before opening Cemu and returns to EmulationStation. I opened a terminal and ran cat ~/logs/extra_patches.log as shown in the Troubleshooting.

![Screenshot from 2024-09-29 17-24-13](https://github.com/user-attachments/assets/b69e32db-58c3-41af-894b-f7f390e394ca)

Noticing the hunk related error I looked in cemuControllers.py and the rejects file to notice that cemuControllers had changed and added API_WIIMOTE = "Wiimote" and was causing the error.

![Screenshot from 2024-09-29 17-31-42](https://github.com/user-attachments/assets/6b3e44f8-c58f-4e31-a265-22a9d95213c0)

https://github.com/git-developer/batocera-extra/blob/main/extra_patches/patch-cemu-generator-for-cemuhook does not have the new WIIMOTE code in here in between line 16 and 21 which is why it's crashing I assume? More noticeably it says to not have been updated since v39 so my best guess is an update for v40 is needed. Thank you in advance and for your hard work and I apologize if I'm missing something.

**Comment by git-developer** [comment]
Thanks for your report and nice words.

Batocera v40 does not contain the Wiimote changes yet. It has been released 2024-08-11, and Wiimote support was added to the codebase on 2024-08-16. It will be part of v41.

Could you please check if you're running v40 or the latest beta release? For the latest beta, checkout batocera-extra from branch `feature/cemu-wiimote`.

**Comment by Uzi043** [comment]
Hello, thank you for responding. My apologizes, I thought I was running stable v40 but I am indeed on Batocera v41 Beta. I guess I should have double checked. On the bright side I checked out the branch like you said and it works perfectly. You are amazing and thank you so much!

**Comment by git-developer** [comment]
You're welcome, nice to hear that.
