### ISSUE TITLE
x86_64 - 41-dev-356fcb0d01，After enable services:extra_patches,unable to launch WiiU games

### ISSUE THREAD

**Issue by Maxwesmart** [git-developer/batocera-extra#11]
for play games with motion,I installed these services.
After enable services:extra_patches,Batocera can‘t  launch any WiiU game.（.wua）
But pressing F1 to enter the cemu-config program allows me to launch WiiU games.

**Comment by git-developer** [comment]
Please check if https://github.com/git-developer/batocera-extra/issues/10 applies to you.

**Comment by git-developer** [comment]
If you're running v41, you have to use branch `feature/cemu-wiimote`. `main` is for v40. It is described in the PR referenced above. Please report back whether this fixes your problem, @Maxwesmart.

**Comment by Maxwesmart** [comment]
I'm sorry for my late reply. The solution you provided is really effective and it solved this issue. Thanks you very much!!!
I think this issue can be closed now. Thanks a lot again



> If you're running v41, you have to use branch `feature/cemu-wiimote`. `main` is for v40. It is described in the PR referenced above. Please report back whether this fixes your problem, @Maxwesmart.
