### ISSUE TITLE
no longer works in v41

### ISSUE THREAD

**Issue by foclabroc** [git-developer/batocera-extra#12]
unfortunately it no longer works in V41 (steamdeck lcd)

**Comment by git-developer** [comment]
If you're running v41, you have to use branch `feature/cemu-wiimote`. main is for v40. It is described in https://github.com/git-developer/batocera-extra/issues/10. Please report back whether this fixes your problem.

**Comment by foclabroc** [comment]
Fixed 👍. Thanks

**Comment by git-developer** [comment]
You're welcome!
