### ISSUE TITLE
Support for aarch64 platform

### ISSUE THREAD

**Issue by git-developer** [git-developer/batocera-extra#6]
Sorry to reopen this but I'm having a similar issue but in aarch64 and v39. Haven't figured out how to fix it yet on my own
batocera-bcm2711-bcm2711-39-20240228.img

```
Using up-to-date local file /userdata/system/.cache/evdevhook2/evdevhook2-v1.0.2-aarch64.AppImage
Installing archlinux package upower in revision 2023-08-03 from repo extra
Error: No URL found in repo 'extra' for package 'upower' in revision '2023-08-03' and arch 'aarch64'
```

_Originally posted by @vickscripts in https://github.com/git-developer/batocera-extra/issues/4#issuecomment-2060332759_

**Comment by git-developer** [comment]
@vickscripts

Motion support requires a few core libraries that are not part of batocera, `upower` being one of them. batocera-extra downloads them from the Arch linux package repository. Unfortunately, Arch linux is `amd64` only, so `upower` is missing for your platform `aarch64`. There not much batocera-extra can do about that.

I see 2 possible solutions:
1. Add `upower` to batocera. It was already part of batocera but was removed. According to this [comment](https://github.com/git-developer/batocera-extra/issues/1#issuecomment-1495394134) by the batocera maintainer, it should be no big deal to enable it. This would be a permanent solution that requires support by the batocera maintainers (or a custom batocera build).
2. Get `upower` and all required dependencies for `aarch64` from elsewhere (or build everything by yourself), and add it to your system in [upowerd-start](https://github.com/git-developer/batocera-extra/blob/batocera-39/bin/upowerd-start). This would be a custom fix just for you that does not require a batocera maintainer or custom build.

I'm not sure if `upower` is a strict requirement or optional. You could try to disable it and see if it works. For example:
```
$ mv /userdata/extra/bin/upowerd-start /userdata/extra/bin/upowerd-start.disabled && ln -s /bin/true /userdata/extra/bin/upowerd-start
```

Once a you found out that a solution or workaround applies, we can check if it can be integrated into batocera-extra.

**Comment by its-vick** [comment]
Thank you for your quick and very detailed response. I'm a novice on Linux and will see what I can get working.
 I've had a few raspberry pis with retropie and with package managers I was able to get joycond-cemuhook or evdevhook2 to work on moonlight or steam link. Recently tried batocera and it is awesome. Found your addition for built in motion support and was thinking it was just what I was looking for. My son's favorite games are on switch and stream via yuzu and steam through raspberry pi.

**Comment by git-developer** [comment]
1. I created a feature request to add upower to batocera (option 1).

2. > I'm a novice on Linux

    OK, no problem. You can find out if `upower` is actually required by changing a single line in the file [/userdata/extra/motion_evdev/start](https://github.com/git-developer/batocera-extra/blob/3969ec521a6c9f438e9d2c7e0df3fefbc1d9ee40/motion_evdev/start#L8): change
```"${base_dir}/../bin/upowerd-start"```
to
```"${base_dir}/../bin/upowerd-start" || true```

3. > My son's favorite games are on switch and stream via yuzu and steam through raspberry pi.

    batocera-extra is not bound to certain emulators, but has been used only for Cemu and Citra so far. yuzu is not officially supported. You might have luck because yuzu comes with integrated motion support and does not require batocera-extra. I have no experience with steam, it might be compatible but could require configuration for "cemuhook" (or "DSU") to host `localhost` and port `26766`.

**Comment by git-developer** [comment]
The feature request has been [implemented](https://github.com/batocera-linux/batocera.linux/pull/11558) so that `upower` will be part of the next batocera release (v40).

**Comment by its-vick** [comment]
Well my problem is somewhat solved. Using motion_nintendo instead.

 tried your suggestion above. With motion_evdev. it makes it further in the process but still missing stuff.

```
Installing archlinux package upower in revision 2023-08-03 from repo extra
Error: No URL found in repo 'extra' for package 'upower' in revision '2023-08-03' and arch 'aarch64'
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

I applied your fix to [/userdata/extra/motion_nintendo/start] and now joycond-cemuhook launches successfully.

```
#!/bin/sh
set -eu
. "$(readlink -f "$(dirname "$0")")/.env"

if "${base_dir}/service" status | grep .; then
  log "${app_name} is already running."
else
  if ! lsmod | grep -q hid_nx; then
    modprobe hid_nx
  fi
  "${base_dir}/../bin/upowerd-start" || true
  ip=192.168.1.228
  PYTHONUNBUFFERED=true joycond-cemuhook ${ip:+--ip "${ip}"} ${port:+--port "${port}"} >>"${log_file}" 2>&1 &
fi

```

in motion_nintendo.log

```
Installing archlinux package upower in revision 2023-08-03 from repo extra
Error: No URL found in repo 'extra' for package 'upower' in revision '2023-08-03' and arch 'aarch64'
Looking for Nintendo Switch controllers...
=============== ('192.168.1.228', 26761) ==============
Device         LED status   Battery Lv   MAC Addr    
               ■ ■ □ □ □    ❌            E4:17:D8:25:CF:06
1 🎮 Pro
2 ❎ 
3 ❎ 
4 ❎ 
=======================================================
```

So now I am able to use this as I had hoped. Successfully getting motion data accessible on an external PC. Im using Batocera on a Pi4b to launch moonlight and steam big picture to launch yuzu.  Thank you so much for your help.

**Comment by git-developer** [comment]
Thanks for your feedback. Nice to see that you could solve / workaround your problem.

Looks like `motion_evdev` has more dependencies that are currently missing on the `aarch64` platform. Fortunately `motion_nintendo` has fewer dependencies and covers your use case.

To keep things sorted, you could move setting your IP to the configuration file `/userdata/extra/motion_nintendo/.env`. You normally don't have to set it manually, is it because your're connecting to `motion_nintendo` from your external PC?

**Comment by its-vick** [comment]
Thank you. Yes joycond-cemuhook defaults to localhost only unless you specify lan IP in arguments.

**Comment by git-developer** [comment]
Hey @vickscripts, I added support for dependencies on ARM platforms (`armhf` and `aarch64`) in branch [feature/arm](https://github.com/git-developer/batocera-extra/tree/feature/arm). I have no suitable hardware to test, though. If you'd like to test it, you can give it a try. If you're happy with motion_nintendo as is, I will keep it until me or someone else is able to test, and we can close this issue.

**Comment by git-developer** [comment]
The error
> ```dlopen(): error loading libfuse.so.2```

is probably caused by a missing dependency FUSE. It may be installed by changing `/userdata/extra/motion_evdev/install` from

```
[…]
  ln -sf "${package}" "/usr/bin/${app_name}"

  if [ "${port}" ]; then
[…]
```

to

```
[…]
  ln -sf "${package}" "/usr/bin/${app_name}"
  "${base_dir}/../bin/install-from-arch" fuse2=?=extra

  if [ "${port}" ]; then
[…]
```

**Comment by its-vick** [comment]
motion_nintendo functions properly and installs all necessary dependencies, including upower.

motion_evdev works as well but with some extra steps.

added to /userdata/extra/motion_evdev/install as you suggested
```
[…]
  ln -sf "${package}" "/usr/bin/${app_name}"
  "${base_dir}/../bin/install-from-arch" fuse2=?=extra

  if [ "${port}" ]; then
[…]
```

after attempting to start motion_evdev I had to do `modprobe fuse`.
switch motion_evdev off and then back on
now evdevhook starts up and functions correctly.

It has an warning which is unrelated to batocera-extra but still functions and outputs motion data retrievable by external pc.

```
Found device Pro Controller (IMU) (unique identifier 'E4:17:D8:25:CF:06') - connecting... done!
** (evdevhook2:9932): WARNING **: 17:54:57.678: EvdevCemuhookDevice.vala:305: Error in battery reader: Error calling StartServiceByName for org.freedesktop.UPower: Launch helper exited with unknown return code 127
```

Thank you for your quick work in making both of those compatible for me.

**Comment by git-developer** [comment]
Thanks a lot for testing! The feature branch is now prepared to install and load FUSE if required, so you might be interested in updating.

The error message probably means that `upower` is not available. This is not critical because it's only required to read out the battery level which is available anyway. I'm nevertheless interested if running `upowerd-start` prints an error message. Would be nice if you could check this whenever you find the time, no problem otherwise.

May I close this issue from your perspective?

**Comment by its-vick** [comment]
Upgraded to latest feature/arm branch.

```
[root@BATOCERA /userdata/extra/bin]# ./upowerd-start
Installing archlinux package 'upower' in revision '2023-08-03' from repo 'extra' for arch 'aarch64'
Using locally cached file /userdata/system/.cache/arch-packages/upower-1.90.2-1-aarch64.pkg.tar.xz
Installing package from /userdata/system/.cache/arch-packages/upower-1.90.2-1-aarch64.pkg.tar.xz
Installing archlinux package 'libimobiledevice' in revision '2023-08-03' from repo 'extra' for arch 'aarch64'
Using locally cached file /userdata/system/.cache/arch-packages/libimobiledevice-1.3.0-9-aarch64.pkg.tar.xz
Installing package from /userdata/system/.cache/arch-packages/libimobiledevice-1.3.0-9-aarch64.pkg.tar.xz
Installing archlinux package 'libplist' in revision '2023-08-03' from repo 'extra' for arch 'aarch64'
Using locally cached file /userdata/system/.cache/arch-packages/libplist-2.3.0-2-aarch64.pkg.tar.xz
Installing package from /userdata/system/.cache/arch-packages/libplist-2.3.0-2-aarch64.pkg.tar.xz
Installing archlinux package 'openssl' in revision '2023-08-03' from repo 'core' for arch 'aarch64'
Using locally cached file /userdata/system/.cache/arch-packages/openssl-3.1.2-1-aarch64.pkg.tar.xz
Installing package from /userdata/system/.cache/arch-packages/openssl-3.1.2-1-aarch64.pkg.tar.xz
Installing archlinux package 'libusbmuxd' in revision '2023-08-03' from repo 'extra' for arch 'aarch64'
Using locally cached file /userdata/system/.cache/arch-packages/libusbmuxd-2.0.2-3-aarch64.pkg.tar.xz
Installing package from /userdata/system/.cache/arch-packages/libusbmuxd-2.0.2-3-aarch64.pkg.tar.xz
```

I'm good with the function of joycond-cemuhook and evdevhook2 in batocera-extra.
I also have a steam controller so I figured I'd test motion_steam_controller on aarch64 for you as well if you're interested.

The log output after switching motion_steam_controller on:
```
[root@BATOCERA /userdata/extra/bin]# Using up-to-date local file /userdata/system/.cache/sc-controller/sc-controller-v0.4.8.13-lunar-aarch64.AppImage
squashfs-root/sc-controller.png
/userdata/extra/motion_steam_controller/install: 39: openbox: not found
```

**Comment by git-developer** [comment]
Thanks! That's strange. `openbox` is the window manager of batocera, it's required to show the Emulation Station GUI. I wonder how that can be missing...
Anyway, just in case you're interested, the workaround for this error is the same as above, this should heal it:
```
DISPLAY=:0 openbox --reconfigure || true
```

**Comment by its-vick** [comment]
`DISPLAY=:0 openbox --reconfigure || true`
That seems to make it install and run. 
I'm unfamiliar with sc-controller. I was unable to get motion data on remote pc. Probably because I had steam controller paired in bluetooth instead of with a dongle. Or possibly in its implementation in [sc-controller](https://github.com/kozec/sc-controller/tree/2e2fe855afff693950827a45637cea3290eae782)/[scc](https://github.com/kozec/sc-controller/tree/2e2fe855afff693950827a45637cea3290eae782/scc)
/cemuhook_server.c 
`server_addr.sin_addr.s_addr = inet_addr("127.0.0.1");`

I don't see a way to specify another IP address similar to joycond-cemuhook.

Either way, I don't plan on using steam controller, was just testing it out.
Thanks for your hard work and my issues are resolved.

**Comment by git-developer** [comment]
Thanks a lot for all your testing.

I agree that sc-controller does not seem to support your use case of a remote client. Unfortunately the project is currently unmaintained. I can make a PR once a new maintainer is found. In the meantime, I built a patched version that allows to set the IP. So, just in case you're curious, the feature branch is updated accordingly. IP and port can be set in `/userdata/extra/motion_steam_controller/.env`, e.g.
```
ip=192.168.1.228
port=26768
```

That worked for me while the controller was connected either via USB or dongle. I didn't test Bluetooth, though.

**Comment by its-vick** [comment]
That's awesome you patched sc-controller to make it accept a different IP. I updated to latest feature/arm branch.
Added `ip=192.168.1.228` to `/userdata/extra/motion_steam_controller/.env`

Tried it out on bluetooth and usb cable and get the following. Seems to crash the program when I connect from yuzu or cemu.

```
[root@BATOCERA /userdata/system]# tail -f /userdata/system/logs/motion_steam_controller.log &
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
W SCCDaemon     Skipping disabled driver 'fake'
W SCCDaemon     Skipping disabled driver 'remotepad'
D USB           Registered USB driver for 054c:09cc
D USB           Registered USB driver for 054c:05c4
D USB           Registered USB driver for 054c:0ce6+
D USB           Registered USB driver for 28de:1102
D USB           Registered USB driver for 28de:1142
D USB           Registered USB driver for 28de:1205
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f8d714fd0>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f8d715950>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f8d717350>
D SCCDaemon     Created control socket /userdata/system/.config/scc/daemon.socket
W SCCDaemon     Wayland detected. Disabling X11 support, some functionality will be unavailable
D asyncio       Using selector: EpollSelector
D SCCDaemon     Assigned default_mapper to <SCByBt scbt1>
D SCCDaemon     Turning gyrosensor ON
D SCCDaemon     Controller added: <SCByBt scbt1>
I CemuHook      Created CemuHookUDP Motion Provider
Traceback (most recent call last):
  File "/tmp/.mount_sc-con2oLW6Z/usr/bin/scc-daemon", line 36, in <module>
    main()
  File "/tmp/.mount_sc-con2oLW6Z/usr/bin/scc-daemon", line 32, in main
    daemon.debug()
  File "/tmp/.mount_sc-con2oLW6Z/usr/lib/python/scc/sccdaemon.py", line 1124, in debug
    self.run()
  File "/tmp/.mount_sc-con2oLW6Z/usr/lib/python/scc/sccdaemon.py", line 672, in run
    fn()
  File "/tmp/.mount_sc-con2oLW6Z/usr/lib/python/scc/poller.py", line 54, in poll
    self._callbacks.get(fd, DO_NOTHING)(fd, Poller.POLLIN)
  File "/tmp/.mount_sc-con2oLW6Z/usr/lib/python/scc/cemuhook_server.py", line 75, in on_data_received
    self._lib.cemuhook_data_received(fd, ip, port, message, len(message), buffer)
ctypes.ArgumentError: argument 2: TypeError: wrong type
```
Also after a system restart, I noticed it requires fuse to be installed/loaded as well. I just started and stopped motion_evdev to accomplish this.

Although I haven't tried to use them other than installing them. motion_sony, motion_wiimote, and motion_remote seem to turn on without errors.

**Comment by git-developer** [comment]
Thanks again for your very valuable feedback!

My patch was broken (the remote ip worked on program start but not on controller connection). It should be fixed now, together with FUSE being installed automatically. The feature branch is updated.

**Comment by its-vick** [comment]
tested updated branch and motion_steam_controller works correctly for remote ip via USB. Thanks for your work.
