### ISSUE TITLE
SteamDeck fails - LIBSYSTEMD_251 not found

### ISSUE THREAD

**Issue by git-developer** [git-developer/batocera-extra#8]
User @foclabroc via discord:

> issue with sdgyrodsu on steamdeck lcd v39
> "sdgyrodsu: /usr/lib64/libsystemd.so.0: version `LIBSYSTEMD_251' not found (required by sdgyrodsu)"

**Comment by git-developer** [comment]
SteamDeckGyroDSU uses systemd since v1.16 (2023-12-01 / Commit [302c836](https://github.com/kmicki/SteamDeckGyroDSU/commit/302c836)). systemd is not part of batocera. I set the version to v1.15 for now ([af82eaa](https://github.com/git-developer/batocera-extra/commit/af82eaa5991bfc1256db29c61e822e669e01d144)).

It should be enough to update to the latest `batocera-39` branch (or manually update the URL in `motion_steam_deck/.env` to 
```url=https://github.com/kmicki/SteamDeckGyroDSU/releases/download/v1.15/SteamDeckGyroDSUSetup.zip```)

An alternative to this downgrade would be to run
```$ install-from-arch systemd-libs=?```
This installs the required dependency in a version compatible to batocera.

I have no hardware to test. Please report back if any of the above proposals work.

**Comment by git-developer** [comment]
The second approach is prepared in branch [fix/steamdeck](https://github.com/git-developer/batocera-extra/tree/fix/steamdeck).

**Comment by foclabroc** [comment]
with SteamDeckGyroDSU v1.15 and chmod everything is ok

**Comment by git-developer** [comment]
Thanks. I added `chmod` to batocera-39 so it should be safe to use again.

If you find the time, it would be nice if you could try the second fix, too. It contains just the old URL and two dependencies ([diff](https://github.com/git-developer/batocera-extra/compare/batocera-39..fix/steamdeck)).

**Comment by git-developer** [comment]
I'm closing this because downgrading to SteamDeckGyroDSU v1.15 fixed the issue. Nevertheless it would be nice if someone could confirm whether the proposed dependency fix also works.
