### ISSUE TITLE
Not able to use Wiimote for Mario Kart 8 Wii U

### ISSUE THREAD

**Issue by patrickpahlke03** [git-developer/batocera-extra#9]
I am not able to connect and use my Wiimote to play Mario kart.

1. I installed batocera-extra
2. Activated extra patches
3. Activated motion_wiimote
4. Connected Wiimote through batocera settings
5. Created default.ini in profiles directory with MAC address in it

linuxmotehook2 is recognizing the remote but in game I can not use it as wheel.

please help

**Comment by git-developer** [comment]
batocera-extra / linuxmotehook2 is a provider for motion only. Configuring the button mappings to use a Wiimote as controller within Cemu is out of this project's scope. I'm not sure if this is currently supported by batocera at all; I once created a feature request on Discord to [Allow real Wiimote in Cemu](https://discord.com/channels/357518249883205632/1171685726782509108). Feel free to join the discussion.

**Comment by patrickpahlke03** [comment]
Am I reading right that with batocera 40 this should work?

**Comment by git-developer** [comment]
I'm not sure about that. dmanlfc created a patched build with SDL enabled, but I can't tell you whether this will be part of v40 or if this change is enough for proper Wiimote support.

**Comment by git-developer** [comment]
I just tried batocera 40. It is possible to play Mario Kart 8 using a Wiimote, including motion. What I did:
1. Pair a Wiimote in the batocera controller menu
2. Configure it as controller, not as zapper
3. Connect a Nunchuck
4. Start the cemu-config (Batocera Main Menu / F1 / Applications)
5. Configure Controller 2 as Wiimote using API Wiimote. Check that the "Motion" checkbox is ticked.
6. Load the game

It can't tell you if these configuration steps are actually required or whether you can simply start Cemu from within ES, I didn't try.

batocera-extra (motion_wiimote) is not required. Thus, I suppose to close this issue, @patrickpahlke03 .

**Comment by git-developer** [comment]
Implemented in https://github.com/batocera-linux/batocera.linux/pull/12291
